import { v4 as uuid } from 'uuid';

export interface Category{
    name:string,
    id:string,
}

export const categories:Array<Category> = [
    {name: 'fruit', id: uuid() },
    {name: 'fall', id: uuid() },
    {name: 'spring', id: uuid() },
    {name: 'fog', id: uuid() },
    {name: 'ocean', id: uuid() },
    {name: 'woman', id: uuid() },
    {name: 'book', id: uuid() },
    {name: 'coffee', id: uuid() },
    {name: 'pet', id: uuid() },
    {name: 'city', id: uuid() },
    {name: 'architecture', id: uuid() },
    {name: 'art', id: uuid() },
    {name: 'vintage', id: uuid() },
    {name: 'light', id: uuid() },
    {name: 'beach', id: uuid() },
    {name: 'flowers', id: uuid() },
    {name: 'mountain', id: uuid() },
    {name: 'moon', id: uuid() },
    {name: 'animal', id: uuid() },
    {name: 'night', id: uuid() },
    {name: 'business', id: uuid() },
    {name: 'trees', id: uuid() },
    {name: 'man', id: uuid() },
    {name: 'abstract', id: uuid() },
    {name: 'water', id: uuid() },
    {name: 'dark', id: uuid() },
    {name: 'space', id: uuid() },
    {name: 'food', id: uuid() },
    {name: 'forest', id: uuid() },
    {name: 'sky', id: uuid() },
    {name: 'cat', id: uuid() },
    {name: 'dog', id: uuid() },
    {name: 'car', id: uuid() },
    {name: 'technology', id: uuid() },
    {name: 'sunset', id: uuid() },
    {name: 'city', id: uuid() },
    {name: 'nature', id: uuid() },
    {name: 'winter', id: uuid() },
    {name: 'sky', id: uuid() },
    {name: 'landscape', id: uuid() },  
];